services:
  mongodb:
    image: mongo:8
    container_name: axiom-mongodb
    restart: unless-stopped

    ports:
      - "27017:27017"

    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:8
    container_name: axiom-redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: axiom-otel-collector
    restart: unless-stopped

    command: ["--config=/etc/otel-collector-config.yaml"]

    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  mongodb_data:
  redis_data: