const GROQ_API_URL = "https://api.groq.com/openai/v1/chat/completions";
const GROQ_MODEL = "llama-3.3-70b-versatile";
const MAX_DURATION_SECONDS = 120;

type FieldType = "string" | "number" | "boolean" | "email" | "date" | "id";

// Same naming heuristics as trafficGenerator's guessValueForField, but
// returns a *type* rather than a value — the model does the value work,
// we just stop it from guessing wrong shapes (e.g. amount as a string).

const MAX_CODE_CONTEXT_CHARS = 6000;

function inferFieldType(field: string): FieldType {
  const lower = field.toLowerCase();
  if (lower.includes("email")) return "email";
  if (lower.includes("date") || lower.endsWith("_at") || lower.endsWith("at"))
    return "date";
  if (lower.startsWith("is") || lower.startsWith("has")) return "boolean";
  if (lower.endsWith("id")) return "id";
  if (
    lower.includes("price") ||
    lower.includes("amount") ||
    lower.includes("total") ||
    lower.includes("qty") ||
    lower.includes("quantity") ||
    lower.includes("count")
  )
    return "number";
  return "string";
}

export interface EndpointMetadata {
  routePath: string;
  method: string;
  appPort: number;
  middlewares: string[];
  authRequired: boolean;
}

export function buildEndpointMetadata(opts: {
  routePath: string;
  method: string;
  appPort: number;
  middlewares: string[];
}): EndpointMetadata {
  return {
    routePath: opts.routePath,
    method: opts.method,
    appPort: opts.appPort,
    middlewares: opts.middlewares,
    authRequired: opts.middlewares.length > 0,
  };
}

function buildPrompt(
  metadata: EndpointMetadata,
  codeContext: string,
  description: string,
): string {
  return `You are a senior performance engineer writing a production-grade k6 load test. Respond with ONLY the script — no markdown fences, no explanation.

Endpoint: ${metadata.method} ${metadata.routePath} on http://localhost:${metadata.appPort}
Auth middleware detected: ${metadata.authRequired ? metadata.middlewares.join(", ") : "none"}

Here is the REAL implementation of this endpoint (route -> controller -> service). This is ground truth — read it carefully rather than guessing the request shape:
${codeContext.slice(0, MAX_CODE_CONTEXT_CHARS)}

User's test scenario, in their own words: "${description}"

Write a k6 script a senior performance engineer would sign off on. Follow every rule below exactly — these are known failure modes, not style preferences:

0. **Read the code above for the exact request body shape and field types — do not invent fields, do not omit fields the code actually destructures from req.body.** Critically: if the code casts an ID field to a MongoDB ObjectId (e.g. via Mongoose \`Schema.Types.ObjectId\`, \`mongoose.Types.ObjectId(...)\`, a model field typed \`ObjectId\`, or a \`findById\`/\`findOne({ _id: ... })\` call), that field MUST be a valid 24-character lowercase hex string in your generated requests — human-readable values like "user-1" will fail Mongoose's cast validation and every request will 500. If the code gives no evidence of ObjectId casting for a given ID-like field, a simple string identifier is fine.

1. **Imports — always include all of these at the top, exactly:**
   \`\`\`
   import http from "k6/http";
   import { check, sleep } from "k6";
   import { Trend } from "k6/metrics";
   \`\`\`
   The script will not run without them.

2. **File header comment** before the imports:
   \`\`\`
   /**
    * Generated by Axiom AI
    *
    * Endpoint: ${metadata.method} ${metadata.routePath}
    * Scenario: <one line from the user's description>
    * Payload fields: <comma-separated field names actually read from req.body in the code above, or "none">
    */
   \`\`\`

3. **JSON payloads, not object literals.** Build the body with \`const payload = JSON.stringify({...})\` and send with \`params\` containing \`headers: { "Content-Type": "application/json" }\`.

4. **Authentication.** ${
    metadata.authRequired
      ? `Read the token from \`__ENV.API_TOKEN\` and add \`Authorization: \`Bearer \${__ENV.API_TOKEN}\`\` to headers. If unset, run anyway but console.warn once at module scope.`
      : "No auth middleware detected — do not add an Authorization header unless the scenario explicitly asks for one."
  }

5. **Realistic data pools. For ID fields that get cast to Mongo ObjectId (see rule 0), generate a REAL 24-character lowercase hex string yourself using a helper function — NEVER use \`crypto.randomUUID()\` for these, since a UUID (e.g. "3f2a9b10-6e51-4c3a-9d21-8a7b5e6f10c2") is NOT a valid ObjectId and will fail Mongoose casting on every single request, silently turning your whole load test into 100% failures.** Declare and use exactly this helper at module scope whenever you need an ObjectId-shaped value:
   \`\`\`
   function generateObjectId() {
     const hex = "0123456789abcdef";
     let id = "";
     for (let i = 0; i < 24; i++) id += hex[Math.floor(Math.random() * 16)];
     return id;
   }
   \`\`\`
   For enum-like fields, declare a small pool array and pick with \`pool[Math.floor(Math.random() * pool.length)]\`. For every other field, generate values matching what the real code above expects.

6. **Think time.** \`sleep(Math.random() * 2)\` after each request.

7. **Metrics.** \`const requestDuration = new Trend("<route_name>_duration");\`, call \`.add(res.timings.duration)\` after every request, plus \`check(res, { "status is success": (r) => r.status >= 200 && r.status < 400 });\`.

8. **Tags on every request:**
   \`\`\`
   http.${metadata.method.toLowerCase()}(url, payload, {
     headers,
     tags: { endpoint: "${metadata.routePath}", scenario: "load-test", generatedBy: "axiom-ai" },
   });
   \`\`\`

9. **Sampled logging, not one line per request, but ALWAYS capture full failure detail.** Near the top: \`const SAMPLE_EVERY = Math.max(1, Math.floor(<expected total iterations> / 150));\`. Every single response still needs to be checked for failure — you cannot skip that check just because logging is sampled. Structure it like this:
   \`\`\`
   const isFailure = res.status === 0 || res.status >= 400;
   if (isFailure || __ITER % SAMPLE_EVERY === 0) {
     console.log("RESULT:" + JSON.stringify({
       status: res.status,
       ok: !isFailure,
       durationMs: res.timings.duration,
       method: "<the HTTP method used for this request>",
       url: url,
       requestBody: isFailure ? payload : undefined,
       body: isFailure ? String(res.body || "").slice(0, 1000) : undefined,
       networkError: isFailure && res.error ? res.error : undefined,
       networkErrorCode: isFailure && res.error_code ? res.error_code : undefined,
     }));
   }
   \`\`\`
   In other words: sampling controls how many *successful* requests get logged, but EVERY failing request gets logged, always, with three things attached: (a) the exact request payload that was sent, (b) the response body truncated to 1000 chars, and (c) k6's own \`res.error\`/\`res.error_code\` for network-level failures where \`res.status\` is 0. No other console.log besides this and the optional one-time auth warning.

10. **Thresholds** sized to the scenario, e.g. \`http_req_failed: ["rate<0.01"]\`, \`http_req_duration: ["p(95)<500"]\`.

11. **VUs/duration or stages** matching the scenario, capped at ${MAX_DURATION_SECONDS}s total.

12. **\`handleSummary(data)\`** using these exact metric paths:
    - \`totalRequests\`: \`data.metrics.http_reqs.values.count\`
    - \`requestsPerSecond\`: \`data.metrics.http_reqs.values.rate\`
    - \`averageLatency\`: \`data.metrics.http_req_duration.values.avg\`
    - \`p95\`: \`data.metrics.http_req_duration.values["p(95)"]\`
    - \`p99\`: \`data.metrics.http_req_duration.values["p(99)"]\`
    - \`errorRate\`: \`data.metrics.http_req_failed.values.rate\` (this is a Rate metric — it has no \`.count\`)
    - \`thresholdsPassed\`:
      \`\`\`
      Object.values(data.metrics)
        .filter((metric) => metric.thresholds)
        .every((metric) => Object.values(metric.thresholds).every((t) => t.ok))
      \`\`\`
    Then \`console.log("SUMMARY:" + JSON.stringify({...}));\` and \`return { stdout: "" };\`.

13. Target exactly \`http://localhost:${metadata.appPort}${metadata.routePath}\`. Self-contained, runnable with \`k6 run\`. Only import from 'k6' and 'k6/metrics'.

14. **Never reassign a value you plan to mutate later using \`const\`.** If the scenario calls for occasionally-invalid values (e.g. sometimes omitting a field, sometimes sending a bad ID), declare that variable with \`let\`, not \`const\` — reassigning a \`const\` throws \`TypeError: Assignment to constant variable\` and silently kills that iteration BEFORE any request is sent, meaning your negative-test cases never actually run and never appear in results. Double-check every variable you conditionally overwrite is declared with \`let\`.

15. **Wrap the entire body of the default exported function in try/catch.** If anything inside throws (a bug in the script itself, not an HTTP error), catch it and log it as its own structured line instead of letting it crash silently to stderr:
    \`\`\`
    export default function () {
      try {
        // ... all iteration logic here ...
      } catch (err) {
        console.log("SCRIPT_ERROR:" + JSON.stringify({
          message: err.message,
          stack: String(err.stack || "").slice(0, 1000),
        }));
      }
    }
    \`\`\`
    This must wrap ALL logic in the default function, including request(s), checks, and logging — the goal is that a bug in the generated script itself is never invisible; it always produces a visible, structured line.`;
}

export interface GeneratedLoadScript {
  script: string;
  authRequired: boolean;
}

// The model is told explicitly (rule 5) never to use crypto.randomUUID()
// for ID fields, since a UUID isn't a valid Mongo ObjectId and will fail
// Mongoose's cast validation on every single request — this has been
// observed to slip through despite the instruction. Rather than let that
// silently 500-storm an entire load test, we mechanically correct it:
// replace crypto.randomUUID() calls with a real 24-char hex ObjectId
// generator, injecting the helper if it isn't already present.
const OBJECT_ID_HELPER = `function generateObjectId() {
  const hex = "0123456789abcdef";
  let id = "";
  for (let i = 0; i < 24; i++) id += hex[Math.floor(Math.random() * 16)];
  return id;
}`;

function fixInvalidIdGeneration(script: string): string {
  if (!/crypto\.randomUUID\s*\(\s*\)/.test(script)) return script;

  const hasHelper = /function\s+generateObjectId\s*\(/.test(script);
  const withHelper = hasHelper ? script : `${OBJECT_ID_HELPER}\n\n${script}`;

  return withHelper.replace(
    /crypto\.randomUUID\s*\(\s*\)/g,
    "generateObjectId()",
  );
}

// Cheap static check for the exact "const later reassigned" bug that
// slipped through in production (see rule 14). We don't try to rewrite
// this one automatically (a real reassignment fix requires understanding
// intent), but we detect obviously reassigned `const` bindings so we can
// at least downgrade `const` -> `let` for the specific case the model
// tends to produce: pool-picked identifiers reassigned inside an if/else
// immediately below their declaration.
function fixConstReassignment(script: string): string {
  const lines = script.split("\n");
  const constNames = new Map<string, number>(); // name -> line index

  const constDeclRe = /^\s*const\s+([a-zA-Z_$][\w$]*)\s*=/;
  const reassignRe = (name: string) => new RegExp(`^\\s*${name}\\s*=[^=]`); // assignment, not `==`/`===`

  for (let i = 0; i < lines.length; i++) {
    const m = lines[i].match(constDeclRe);
    if (m) constNames.set(m[1], i);
  }

  for (const [name, declIndex] of constNames) {
    const re = reassignRe(name);
    for (let i = declIndex + 1; i < lines.length; i++) {
      if (re.test(lines[i])) {
        lines[declIndex] = lines[declIndex].replace(
          new RegExp(`^(\\s*)const(\\s+${name}\\s*=)`),
          "$1let$2",
        );
        break;
      }
    }
  }

  return lines.join("\n");
}

export async function generateLoadScript(opts: {
  metadata: EndpointMetadata;
  codeContext: string;
  description: string;
}): Promise<GeneratedLoadScript> {
  const apiKey = process.env.GROQ_API_KEY;
  if (!apiKey) {
    throw new Error("GROQ_API_KEY is not configured on the server.");
  }

  const response = await fetch(GROQ_API_URL, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model: GROQ_MODEL,
      messages: [
        {
          role: "system",
          content:
            "You are a senior performance engineer who writes production-grade k6 scripts, grounded in the real backend code you're shown — never inventing a request shape that contradicts it. JSON payloads, proper auth, correct ID formats (real 24-char hex ObjectIds when the code casts to one — never crypto.randomUUID()), realistic data pools declared with `let` if later reassigned, think time, Trend metrics, thresholds, a try/catch-wrapped iteration body that logs its own errors, always-logged failure detail (request payload + response body + k6 network error/error_code), and a structured JSON summary. Respond with raw JavaScript only.",
        },
        {
          role: "user",
          content: buildPrompt(
            opts.metadata,
            opts.codeContext,
            opts.description,
          ),
        },
      ],
      temperature: 0.4,
      max_tokens: 1800,
    }),
  });

  if (!response.ok) {
    const errBody = await response.text().catch(() => "");
    throw new Error(
      `Groq API error (${response.status}): ${errBody.slice(0, 200)}`,
    );
  }

  const data = await response.json();
  let script: string | undefined = data.choices?.[0]?.message?.content;
  if (!script) throw new Error("Groq API returned no script");

  script = script
    .trim()
    .replace(/^```(?:javascript|js)?\n?/, "")
    .replace(/```$/, "")
    .trim();

  // Mechanical safety net: correct known failure modes regardless of
  // whether the model followed the prompt's rules, so a bad generation
  // doesn't silently produce a 100%-failing or crash-looping test.
  script = fixInvalidIdGeneration(script);
  script = fixConstReassignment(script);

  return { script, authRequired: opts.metadata.authRequired };
}
