export interface GeneratedFile {
  id: string;
  name: string;
  language: "javascript" | "ini" | "markdown";
  content: string;
}

export interface InstrumentationResult {
  files: GeneratedFile[];
  runCommand: string;
  estimatedSetupSeconds: number;
}

/** "AymaanPathan/E-commerce" -> "e-commerce" */
function toServiceSlug(githubFullName: string): string {
  const repoName = githubFullName.split("/")[1] ?? githubFullName;
  return repoName
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function buildInstrumentationFile(serviceSlug: string): string {
  return `import { NodeSDK } from "@opentelemetry/sdk-node";
import { getNodeAutoInstrumentations } from "@opentelemetry/auto-instrumentations-node";
import { OTLPTraceExporter } from "@opentelemetry/exporter-trace-otlp-http";
import { resourceFromAttributes } from "@opentelemetry/resources";
import { ATTR_SERVICE_NAME } from "@opentelemetry/semantic-conventions";

const traceExporter = new OTLPTraceExporter({
  url: process.env.OTEL_EXPORTER_OTLP_ENDPOINT
    ? \`\${process.env.OTEL_EXPORTER_OTLP_ENDPOINT}/v1/traces\`
    : "http://localhost:4318/v1/traces",
});

const sdk = new NodeSDK({
  resource: resourceFromAttributes({
    [ATTR_SERVICE_NAME]: process.env.OTEL_SERVICE_NAME || "${serviceSlug}",
  }),
  traceExporter,
  instrumentations: [getNodeAutoInstrumentations()],
});

sdk.start();

console.log("✅ OpenTelemetry Initialized for ${serviceSlug}");

process.on("SIGTERM", async () => {
  await sdk.shutdown();
});
`;
}

function buildEnvFile(serviceSlug: string): string {
  return `# Generated by Axiom AI — safe to commit, contains no secrets
OTEL_SERVICE_NAME=${serviceSlug}
OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4318
OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
OTEL_NODE_RESOURCE_DETECTORS=env,host,os
`;
}

function buildReadme(
  githubFullName: string,
  serviceSlug: string,
  entryFileGuess: string,
): string {
  return `# Axiom AI — Instrumentation Setup

Generated for **${githubFullName}**. No source files were modified — these
are standalone files you drop into the project.

## 1. Install dependencies

\`\`\`
npm install @opentelemetry/sdk-node @opentelemetry/auto-instrumentations-node \\
  @opentelemetry/exporter-trace-otlp-http @opentelemetry/resources \\
  @opentelemetry/semantic-conventions
\`\`\`

## 2. Start SigNoz locally

Follow the SigNoz quick start (https://signoz.io/docs/install/) if you don't
already have it running. By default it listens for OTLP traces on
\`http://localhost:4318\`.

## 3. Run your app with instrumentation

\`\`\`
node --require ./axim.instrumentation.js ${entryFileGuess}
\`\`\`

Swap \`${entryFileGuess}\` for your actual entry file if it's different.

## 4. Send requests

Hit the routes Axiom AI discovered — \`/products\`, \`/checkout\`, etc.

## 5. Watch traces

Open SigNoz at \`http://localhost:3301\`, go to **Traces**, and filter by
service name \`${serviceSlug}\`.
`;
}

export function generateInstrumentation(
  githubFullName: string,
): InstrumentationResult {
  const serviceSlug = toServiceSlug(githubFullName);
  const entryFileGuess = "server.js";

  const files: GeneratedFile[] = [
    {
      id: "instrumentation",
      name: "axim.instrumentation.js",
      language: "javascript",
      content: buildInstrumentationFile(serviceSlug),
    },
    {
      id: "env",
      name: ".env.otel",
      language: "ini",
      content: buildEnvFile(serviceSlug),
    },
    {
      id: "readme",
      name: "README.md",
      language: "markdown",
      content: buildReadme(githubFullName, serviceSlug, entryFileGuess),
    },
  ];

  return {
    files,
    runCommand: `node --require ./axim.instrumentation.js ${entryFileGuess}`,
    estimatedSetupSeconds: 15,
  };
}
